name: essai
description: "esai de dashboard"

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.63.0
  intl: ^0.18.0
  http: ^1.2.2



  flutter_local_notifications: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: '>=3.5.0'